### PR TITLE
rc/v2.1.3

### PR DESCRIPTION
**Pull request by zsigmas**
closes: #6
closes: #16  

# Critical checks

- [x] Is the version number correct?

  - [x] DESCRIPTION file

  - [x] [NEWS.md](http://news.md/)

- [x] Does the build pass?

---

## Documentation

Does it include the following sections?

- [x] Module introduction with features

  - [x] (O) Screenshots

- [x] Installation details

- [x] Explanation of function arguments

- [x] Data specifications and requirements

- [x] Different possible visualizations

-  [x] Are the changes/new features included in [NEWS.md?](http://news.md/)

  - [x] (O) Screenshots

- [x] (O) Explanation of input menus

- [x] (O) Short articles on building the app, compatibility with other modules, known bugs,...

---

## QC Report

- [x] Does it include a QC Report?

---

## API conventions

- [x] Follows API convention

### CODE REVIEW

**Comment by zsigmas** [comment]
[72393a7](https://github.com/Boehringer-Ingelheim/dv.manager/pull/20/commits/72393a7c3015ea09119d7806d8575ae89d396605) and [136d43f](https://github.com/Boehringer-Ingelheim/dv.manager/pull/20/commits/136d43fbb0820c213e9a685cc67e4a62a89abb0f)

Cover a curious case in which we try to retrieve the value from an input that is blocked by request(FALSE), as the appDriver does not know anything about the internals of the app it returns list() which may be confusing when testing.

**Comment by zsigmas** [comment]
Pending on final decision of Global filter and Dataset filter titles

**Comment by zsigmas** [comment]
closes #22

**Comment by zsigmas** [comment]
closes #24 
closes #22

**Review by ml-ebs-ext — APPROVED** [review]

**Pull request merged**
